// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePostInput struct {
	Title         string `json:"title"`
	Body          string `json:"body"`
	UserID        string `json:"userId"`
	AllowComments bool   `json:"allowComments"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
