// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateCommentInput struct {
	Body     string  `json:"body"`
	UserID   string  `json:"userId"`
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
}

type CreatePostInput struct {
	Title         string `json:"title"`
	Body          string `json:"body"`
	UserID        string `json:"userId"`
	AllowComments bool   `json:"allowComments"`
}

type Mutation struct {
}

type Query struct {
}
